apiVersion: v1
kind: Service
metadata:
  name: jo-service-nodeport1
spec: 
  type: NodePort
  selector: 
    app: chats  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: jo-service-nodeport2
spec: 
  type: NodePort
  selector: 
    app: status  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001